### ISSUE TITLE
Feature request: Quote tweets

### ISSUE THREAD

**Issue by phil-bradbury** [robinuniverse/TwitFix#10]
Fixing videos is super handy, but why stop there? Would be awesome to try to fix other types of tweets that embed poorly in Discord, and after videos, second on the list is QTs...

**Comment by robinuniverse** [comment]
The main limitation is needing to get directly embedable direct video links, without actually downloading the video itself, this is made possible for twitter through the twitter API and youtube-dl's info downloader, but as i've seen from trying the same trick on many other sites, direct MP4 links are rarely available - [Here is a short list of sites I have tested with the same method I use for twitter and the reasons they don't work ](https://docs.google.com/spreadsheets/d/1mRXmsEFXn8xz8z3kQAk6pu0ummSi9BZw7N_KJd-HCiw/edit#gid=0)

**Comment by robinuniverse** [comment]
QRTs are kinda halfway fixed, ish, I'm automatically redirecting to t.co links in non video tweets, but the main problem is for some reason tweets embed differently and quite a lot worse when embeded from a t.co link. Only way I can reckon working around this is doing a request on every t.co link to unfurl it, but this would significantly increase network load on the server I think, so I'm not sure if I want to do it

**Comment by cooljeanius** [comment]
> Fixing videos is super handy, but why stop there? Would be awesome to try to fix other types of tweets that embed poorly in Discord, and after videos, second on the list is QTs...

I'd add polls to that list, too
