### ISSUE TITLE
Aesthetic Request: Changing the default embed color to blue

### ISSUE THREAD

**Issue by Jecket22** [robinuniverse/TwitFix#11]
This might be a bit of a stretch to make a request solely for changing the embed color, but I thought that the green bar for TwitFix embeds doesn't fit considering embeds for Twitter links have a blue bar.

If I'm correct, the color of the bar from the Twitter embeds should be `#1DA0F2`.

**Comment by robinuniverse** [comment]
I have chosen green as a way to differentiate twitfix from native twitter embeds, it's on purpose, but yesterday I did add the color parameter to the config file, so if other people run their own instance of the server it can be changed to whatever the like by changing the `color` key
