### ISSUE TITLE
[Feature request] Telegram support

### ISSUE THREAD

**Issue by Izofeu** [robinuniverse/TwitFix#13]
Telegram completely ignores the fixed embed and just shows a regular embed with videos as images. Is it possible to make this work with Telegram too?

**Comment by robinuniverse** [comment]
I reckon it's possible to make embeds specific to any platform by checking against the useragent and serving a different page based on that, but I don't personally use telegram, so adding support for it is pretty low on my radar - I will look into it at some point though, if no one comes around to do a PR for it first

**Comment by Izofeu** [comment]
I made some tweaks to the code and got it working but I'm not the greatest coder and my code is a bit messy. Would it be ok to submit a pull request and have someone take a look?

**Comment by robinuniverse** [comment]
Oh yes please do!

**Comment by Izofeu** [comment]
#14
