### ISSUE TITLE
tweets with ids not 19 digits long are not matched

### ISSUE THREAD

**Issue by ttpcodes** [robinuniverse/TwitFix#17]
[the current regex](https://github.com/robinuniverse/TwitFix/blob/f19e3387ba1e92943e0573c17d7660028c66f127/twitfix.py#L11) for parsing a tweet url only checks for tweet ids that are 19 digits long. however, there **are** tweet ids shorter than 19 digits, and twitfix currently doesn't handle them correctly (right now the behavior is to redirect, which has the behavior of #12).

the easiest way to demonstrate this behavior is to look for any tweet prior to approximately 2018 may 25, as that's around the timestamp that splits up 18 digit and 19 digit tweet ids. any tweet prior to this date results in the redirect behavior, and any tweet after approximately 2018 may 26th is handled properly.

the specification that twitter uses for generating their twitter ids is described [here](https://en.wikipedia.org/wiki/Snowflake_ID), and it's essentially a 64-bit integer, meaning that it's possible for tweets to go up to 20 digits long. i'm not sure the shortest id length is for a tweet that can be handled by twitfix is, but i do know that the earliest tweet that still exists is [by jack dorsey and is twitter id 20 (two digits long)](https://ws-dl.blogspot.com/2019/08/2019-08-03-tweetedat-finding-tweet.html).

the best way to fix this would probably be to modify the regex to parse ids that are anywhere from 2 to 20 digits long, which should guarantee that all currently existing tweets can be handled.

**Comment by robinuniverse** [comment]
yeah, this is a good catch, I'm kinda aware of this problem and have intended to fix it, I just really suck with regex to be honest and have been putting it off :sweat_smile: 

Don't worry, I'll be fixed

**Comment by adryd325** [comment]
I'll make a quick PR

**Comment by robinuniverse** [comment]
That did the trick, it's merged and pushed to prod. Thank you again @adryd325
