### ISSUE TITLE
Add twitter text to embeds 

### ISSUE THREAD

**Issue by ATSchell** [robinuniverse/TwitFix#2]
Some context can be lost on embedding a video if text is related to the video/media.  If you can pull text from twitter, it may be easy to display this text along with the image by putting them in html meta content. 
## Code example 
```html
<meta content = "Embed Title" property= [user name] /> 
<meta content = "Content" property= [tweet text] />
<meta content = "Content" property= [video URL] />
```

**Comment by robinuniverse** [comment]
I agree that being able to do something like this would be nice but a lot of experimenting will need to be done to see what kind of embed syntax can be interpreted correctly by discord to be able to show both a description, title, and embedded video

**Comment by robinuniverse** [comment]
I was able to get this issue solved by creating and using an oEmbed json endpoint :)
![clip](https://user-images.githubusercontent.com/12601774/125066839-14d37880-e079-11eb-9ca6-9bd555616d06.png)
