### ISSUE TITLE
Some video cannot be "fast forward-ed"

### ISSUE THREAD

**Issue by OshidaBCF** [robinuniverse/TwitFix#21]
On some video that get "converted" you can't jump to a certain timestamp.
But it doesn't happen forever.
After a while it seem that the video now can be accessed at all timestamps.
i can't provide exemple because the only link that didn't worked now works.

**Comment by robinuniverse** [comment]
I think it might have to do with how the figure loads in, it's not exactly the same as most vids, gonna chalk it up to a discord embed limitation as I have very little control how vids are actually presented. Don't think I can do anything to fix it unless anyone has any ideas for a specific fix

**Comment by OshidaBCF** [comment]
okay that make sense.
