### ISSUE TITLE
Tweet text sliced at `&` character?

### ISSUE THREAD

**Issue by tw0517tw** [robinuniverse/TwitFix#23]
original tweet: https://twitter.com/trysail_staff/status/1421674805036650496
![圖片](https://user-images.githubusercontent.com/1003146/127758886-71417884-725e-4e01-887f-1094810c0100.png)

fxtwiiter on discord:
![圖片](https://user-images.githubusercontent.com/1003146/127758867-b3c025f4-197a-494f-be76-88b57d1bfbe4.png)

maybe is kind of injection due to the `&` character?

**Comment by robinuniverse** [comment]
Fixed, tested, and pushed to prod. Thanks @adryd325
