### ISSUE TITLE
Louder videos clip on discord when they don't on twitter

### ISSUE THREAD

**Issue by brubsby** [robinuniverse/TwitFix#26]
for example https://fxtwitter.com/MoonlessShift/status/1423325696613666821 this hard clips when played back on discord at 100% volume, but on twitter at 100% volume it doesn't.

![image](https://user-images.githubusercontent.com/57653502/128578610-e739c4c1-f228-4360-950b-ff949cb36a56.png)
discord vs twitter recording in audacity

**Comment by robinuniverse** [comment]
Unfortunately the player stuff is all handled by electron/discords side so there's not much I can do to solve this, as I'm just reposting the direct links to the video stored on twitters server, only viable fix would be to download each vid and reencode them with tweaked audio, which is not feasible at the scale twitfix runs at with my hardware

**Comment by brubsby** [comment]
ah, makes sense then, i thought maybe you were converting the audio stream to a different format that didn't handle above 0db or something. thanks for the explanation!
