### ISSUE TITLE
normal tweets without images or videos get Failed to scan your link! error

### ISSUE THREAD

**Issue by mina9999** [robinuniverse/TwitFix#31]
i made a discord bot for twitter and when people tweet it shows Failed to scan your link!
like this:
https://fxtwitter.com/twice_pix/status/1440065806327418904
also the images shows on thumbnail not on image part.
like : https://fxtwitter.com/twice_pix/status/1440023930631344135
they are too small. thank you for your amazing work but please fix it.
here is proof: 
![image](https://user-images.githubusercontent.com/28566705/134078963-c87c6a67-0b03-4b52-8cd5-af6971d1b26b.png)

**Comment by robinuniverse** [comment]
TwitFix is not currently set up to handle non-video links, as it's not really intended to fix embeds for non video tweets. I have an idea for how to work around, ( Using the Twitter API to detect non video links, and then redirecting the original link back to the Discord useragent ) but I have not had the time or need to implement this. If you need a bot that can automatically detect twitter video links and post them, then you should consider hosting a copy of my other project, [TwitFix-Bot](https://github.com/robinuniverse/TwitFix-Bot)
