### ISSUE TITLE
fxtwitter.com getting 502 Bad Gateway error

### ISSUE THREAD

**Issue by Gestrid** [robinuniverse/TwitFix#32]
I just tried to use the site to embed a Twitter video in Discord, but the tweet wasn't showing up when I posted the link. So I tried pasting the link into my browser, and that's what gave me the 502 Bad Gateway error.

"Is It Down Right Now?" also reports that the website is down for everyone: https://www.isitdownrightnow.com/fxtwitter.com.html

**Comment by robinuniverse** [comment]
Thanks for the heads up! I've got it back up and running again
