### ISSUE TITLE
Expired Certificate?

### ISSUE THREAD

**Issue by blunttheking** [robinuniverse/TwitFix#35]
so i tried to post a twitter link today, but it didn't embed. When I clicked the fxtwitter link, it lead to this.

looks like the site's certificate expired earlier today.

![image](https://user-images.githubusercontent.com/78389756/135946388-eee1c150-a367-4a82-b6fb-385cae9f45f7.png)

**Comment by robbiet480** [comment]
Confirmed, certificate expired yesterday.

**Comment by robinuniverse** [comment]
Certificate renewed, and autorenew set up, thanks for the heads up
