### ISSUE TITLE
vidlink not set in embed

### ISSUE THREAD

**Issue by cbondurant** [robinuniverse/TwitFix#37]
in `embed` currently there is no argument for the value `vidlink` in the `index.html` template.

I believe this is causing endless loops in some contexts. Such as with the `/other/` route

Example link:
https://fxtwitter.com/other/Twitter/status/1410227743636217856

on my machine this link will endlessly attempt to reload as a result of the `<meta http-equiv = "refresh" content = "0; url = " />` tag.

**Comment by robinuniverse** [comment]
Addressed and fixed (hopefully)
