### ISSUE TITLE
Issue with planned feature

### ISSUE THREAD

**Issue by TheTechn0mancer** [robinuniverse/TwitFix#38]
https://github.com/robinuniverse/TwitFix/projects/1#card-65378657
This shouldn't be added because it would make both this project and Discord itself worse off.

**Comment by robinuniverse** [comment]
which one? the link doesn't appear to work

**Comment by TheTechn0mancer** [comment]
Adding T*kT*k support

**Comment by robinuniverse** [comment]
I don't see how adding support for another platform would make anything worse off
