### ISSUE TITLE
Image embeds only show a small preview

### ISSUE THREAD

**Issue by thakyZ** [robinuniverse/TwitFix#40]
I would like to see if it would be possible for you to make it, so the image preview for  image links show the full size image, much like it does with videos.
Here is what it looks like now
![image](https://user-images.githubusercontent.com/950594/146659313-5532c8c5-3e93-458a-8cc5-1c1b9153b2fa.png)

**Comment by robinuniverse** [comment]
using twitfix for non video tweets is not an intended use case. Of course, I know me saying that has not dettered people in the past, so I might as well make the unintended usages of twitfix at least look halfway decent, so fixing this is on the todo list, but it's at a pretty low priority. Of course, with everything, I'm always open to PRs addressing the issue, but as it stands it will probably be a while before I get to this

**Comment by logoffon** [comment]
Raising this up as Twitter embeds are now completely broken (i.e. nothing at all) in the past 12 hours and twitfix is only showing user's avatar. Would be a nice addition for use in cases like this.

**Comment by robinuniverse** [comment]
I have completed this, it's not in the repo yet, but it's live
