### ISSUE TITLE
Video embeds for fxtwitter now only display the thumbnail

### ISSUE THREAD

**Issue by MacMJ3** [robinuniverse/TwitFix#43]
While posting a link to a tweet containing a video and using fxtwitter the post only displayed the thumbnail and not option to play a video could be selected.

I tested on both browser and desktop discord and the same result occurs.

![fxtwitter_embed_disabled](https://user-images.githubusercontent.com/54540733/153696927-715e73c5-1b61-4228-bdfb-d1d435f8efe3.png)

**Comment by robinuniverse** [comment]
Shoot my bad! thanks for bringing this to my attention

**Comment by robinuniverse** [comment]
Fixing now and restarting the server
