### ISSUE TITLE
FxTwitter not embedding on select tweets

### ISSUE THREAD

**Issue by MacMJ3** [robinuniverse/TwitFix#45]
Hello, I wanted to report that it seems like FxTwitter isn't embedding for some tweets as of late. I attached two screenshots of it not working in desktop or browser discord. 
![Discord_Browser](https://user-images.githubusercontent.com/54540733/157108117-5636a10b-cb53-44aa-a60e-baa3ac18d7cb.png)
![Discord_Desktop](https://user-images.githubusercontent.com/54540733/157108118-03d51b72-8a20-480e-9305-4e544ab421f9.png)

**Comment by robinuniverse** [comment]
Unforunately I am aware of this. Twitter seems to have either revoked or severely limited my API access. Hoping to get it resolved

**Comment by MacMJ3** [comment]
> Unforunately I am aware of this. Twitter seems to have either revoked or severely limited my API access. Hoping to get it resolved

Dang I'm sorry to hear this. Hope it gets fixed.
