### ISSUE TITLE
Feature Request: Cross-Embeds

### ISSUE THREAD

**Issue by madprogramer** [robinuniverse/TwitFix#5]
Finally being able to share Twitter videos on Discord? Awesome.

Being able to embed YouTube or Vimeo links on Tweets? **Would be even more awesome**.

Ex. if https://fxtwitter.com/DataHordeBlog/status/1414615545752608774 could embed https://youtu.be/kIaM7q4OrIw or alternatively the Twitter shortlink of https://t.co/zoMVnZuXN3

I think `/other/<video-url>` will eventually be used for this, but I would love to see it working some time soon :}

**Comment by robinuniverse** [comment]
This is an interesting idea, but it's kind of out of scope for my ideas of the project, and I don't even know what the first step to approaching a solution to this would be, I'm going to continue to focus on making the intended function work as well as I can get it, but if anyone else comes along and would like to make some PRs to that affect I am not against that whatsoever, thank you for the suggestion, though

**Comment by robinuniverse** [comment]
Ok so upon further investigation this might actually be possible by using some funky useragent redirection stuff

**Comment by robinuniverse** [comment]
Alright, I was able to get this pulled off, and it's now pushed to prod. Luckily t.co links require no unfurling to embed directly to discord, so in non video links, I check for t.co links, and then redirect the discord useragent directly to the first link in any given non video twet. This should allow for basically native embedding of every link that it can see

**Comment by madprogramer** [comment]
Wow that was fast! Even though I didn't do much I'm glad my t.co idea actually amounted to something.

![image](https://user-images.githubusercontent.com/3719664/126014805-f1312739-c26f-4e7c-bebb-7dd5a0e59f9c.png)

That being said, I noticed that the embed template seems to be missing all the information related to the Tweet itself. 

![image](https://user-images.githubusercontent.com/3719664/126014975-925873c0-c1de-4009-8b6b-64c96b116c2a.png)

The tweet body, account info etc. Though maybe I should have opened a new issue for this :)

**Comment by robinuniverse** [comment]
As it stands, I don't see a way to make both possible, I currently don't even have a way to show the content of non video tweets anyways, so I figure if that content is needed then the native tweet embed will probably be better, this just adds options

**Comment by madprogramer** [comment]
Welp, I have actually found a hacky workaround. By including one copy of the Twitter link (which I know will fail to embed) and one copy of the fxtwitter link I can embed both the tweet info and external link.

![image](https://user-images.githubusercontent.com/3719664/126068862-4c86fa28-40de-429e-97ca-4367bb791e19.png)

Is it super different from having two links? Maybe not. But it sure is a lot more convenient!
