### ISSUE TITLE
Feature Request: Embed color change

### ISSUE THREAD

**Issue by ajl223** [robinuniverse/TwitFix#9]
Ability to change the color from green to something like blue by adding something like `/color/#FFFFFF` (url fragments) I cant think of anything else but yeah

**Comment by robinuniverse** [comment]
Oh, yeah that's cool. I don't know how practical it is to make it part of the URL but I can defo put it in the config

**Comment by robinuniverse** [comment]
Alright I added color as part of the config last night, so at least it can be changed easily if running your own instance of the server
